-- Esquema inicial de MiNutria.
--
-- Reemplaza a ddl-auto=update, que servia para desarrollar pero no puede ir a
-- produccion: nunca borra una columna que sacaste del codigo, nunca corrige un
-- tipo que cambio, no deja historial de que se aplico, y no migra datos.
--
-- REGLA DE ORO DE FLYWAY: una migracion ya aplicada NO SE EDITA NUNCA. Flyway
-- guarda un checksum de cada archivo; si cambia, la app se niega a arrancar.
-- Para corregir algo, se escribe una V2 nueva.

CREATE TABLE grupo (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL
);

CREATE TABLE usuario (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    -- 100 alcanza para BCrypt, que produce hashes de 60 caracteres.
    password_hash VARCHAR(100) NOT NULL,
    grupo_id      BIGINT       NOT NULL,

    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_grupo FOREIGN KEY (grupo_id) REFERENCES grupo (id)
);

CREATE TABLE categoria (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    icono  VARCHAR(50) NOT NULL,

    CONSTRAINT uk_categoria_nombre UNIQUE (nombre)
);

CREATE TABLE gasto (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id       BIGINT         NOT NULL,
    pagado_por_id  BIGINT         NOT NULL,
    categoria_id   BIGINT         NOT NULL,

    -- NUMERIC y no punto flotante: 0.10 no tiene representacion binaria exacta
    -- y el error se acumula sumando gastos.
    monto          NUMERIC(12, 2) NOT NULL,
    -- El reparto se guarda RESUELTO, no como porcentaje. Asi el redondeo del
    -- centavo impar se decide una sola vez al escribir, y la deuda que genera
    -- el gasto es una resta: monto - monto_pagador.
    monto_pagador  NUMERIC(12, 2) NOT NULL,

    tipo           VARCHAR(20)    NOT NULL,
    -- La marca de gasto evitable. Es el dato central del producto y solo lo
    -- puede decidir quien carga el gasto: el mismo uber por el mismo monto es
    -- necesario o evitable segun el motivo.
    es_hormiga     BOOLEAN        NOT NULL,
    fecha          DATE           NOT NULL,
    descripcion    VARCHAR(255)   NOT NULL,

    creado_en      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    actualizado_en TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- Bloqueo optimista: Hibernate agrega "AND version = ?" a cada UPDATE.
    version        BIGINT         NOT NULL,

    CONSTRAINT fk_gasto_grupo      FOREIGN KEY (grupo_id)      REFERENCES grupo (id),
    CONSTRAINT fk_gasto_pagado_por FOREIGN KEY (pagado_por_id) REFERENCES usuario (id),
    CONSTRAINT fk_gasto_categoria  FOREIGN KEY (categoria_id)  REFERENCES categoria (id),

    -- Ultima linea de defensa: si un bug del servicio deja pasar un valor
    -- imposible, la base no lo escribe.
    CONSTRAINT ck_gasto_monto_positivo CHECK (monto > 0),
    CONSTRAINT ck_gasto_reparto_valido CHECK (monto_pagador >= 0 AND monto_pagador <= monto),
    CONSTRAINT ck_gasto_tipo           CHECK (tipo IN ('PERSONAL', 'COMPARTIDO'))
);

-- Sostiene el listado del mes, el saldo y el total hormiga: los tres filtran
-- por grupo y rango de fechas.
CREATE INDEX idx_gasto_grupo_fecha ON gasto (grupo_id, fecha);

-- Para el filtro "pagado por".
CREATE INDEX idx_gasto_pagado_por ON gasto (pagado_por_id);
